CREATE VIEW top_2_hits_do_momento AS
SELECT COUNT(HM.MUSIC_ID) AS reproducoes, M.MUSIC_NAME AS cancao FROM SpotifyClone.HISTORY_MUSIC AS HM
INNER JOIN MUSIC AS M
ON M.MUSIC_ID=HM.MUSIC_ID
GROUP BY HM.MUSIC_ID
HAVING HM.MUSIC_ID > 0 
ORDER BY COUNT(HM.MUSIC_ID) DESC
LIMIT 2
;