CREATE VIEW perfil_artistas AS
SELECT a.ARTIST_NAME AS artista, al.ALBUM_NAME AS album, COUNT(fa.ARTIST_ID) AS seguidores FROM SpotifyClone.ARTIST AS a
INNER JOIN ALBUM AS al
ON al.ARTIST_ID=a.ARTIST_ID
INNER JOIN FOLLOWED_ARTISTS AS fa
ON a.ARTIST_ID=fa.ARTIST_ID
GROUP BY a.ARTIST_NAME, al.ALBUM_NAME
HAVING COUNT(fa.ARTIST_ID) > 0
ORDER BY COUNT(fa.ARTIST_ID) DESC , a.ARTIST_NAME, al.ALBUM_NAME
;
