CREATE VIEW top_3_artistas AS
SELECT A.ARTIST_NAME AS artista ,COUNT(FA.ARTIST_ID) AS seguidores 
FROM SpotifyClone.FOLLOWED_ARTISTS AS FA
INNER JOIN ARTIST AS A
ON A.ARTIST_ID=FA.ARTIST_ID
GROUP BY FA.ARTIST_ID
HAVING FA.ARTIST_ID > 0
ORDER BY COUNT(FA.ARTIST_ID) DESC
LIMIT 3;
