USE SpotifyClone;
DELIMITER $$
CREATE FUNCTION quantidade_musicas_no_historico(id INT)
RETURNS INT READS SQL DATA
BEGIN
DECLARE historico INT;
SELECT
COUNT(H.CANCAO_ID) 
FROM SpotifyClone.USUARIOS AS U
INNER JOIN SpotifyClone.HIST_REPRODUCOES AS H
ON U.USUARIO_ID = H.USUARIO_ID
WHERE U.USUARIO_ID = id
GROUP BY U.USUARIO_ID
INTO historico;
RETURN historico;
END $$
DELIMITER ;
