CREATE DATABASE IF NOT EXISTS SpotifyClone;
USE SpotifyClone;

CREATE TABLE PLANO(
PLANO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_DO_PLANO VARCHAR(50) NOT NULL,
VALOR_DO_PLANO DECIMAL(5,2) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE USUARIOS(
USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
IDADE INT NOT NULL,
PLANO_ID INT NOT NULL,
FOREIGN KEY (PLANO_ID) REFERENCES PLANO(PLANO_ID)
) ENGINE = InnoDB;

CREATE TABLE ARTISTAS(
ARTISTA_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_DO_ARTISTA VARCHAR(50) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE ALBUNS(
ALBUM_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_DO_ALBUM VARCHAR(50) NOT NULL,
ARTISTA_ID INT NOT NULL,
FOREIGN KEY (ARTISTA_ID) REFERENCES ARTISTAS(ARTISTA_ID)
) ENGINE = InnoDB;

CREATE TABLE CANCOES(
CANCAO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_DA_CANCAO VARCHAR(50) NOT NULL,
ALBUM_ID INT NOT NULL,
FOREIGN KEY (ALBUM_ID) REFERENCES ALBUNS(ALBUM_ID)
) ENGINE = InnoDB;

CREATE TABLE HIST_REPRODUCOES(
USUARIO_ID INT NOT NULL,
CANCAO_ID INT NOT NULL,
CONSTRAINT PRIMARY KEY(USUARIO_ID,CANCAO_ID),
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID),
FOREIGN KEY (CANCAO_ID) REFERENCES CANCOES(CANCAO_ID)
) ENGINE = InnoDB;

CREATE TABLE SEGUINDO_ARTISTAS(
USUARIO_ID INT NOT NULL,
ARTISTA_ID INT NOT NULL,
CONSTRAINT PRIMARY KEY(USUARIO_ID,ARTISTA_ID),
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID),
FOREIGN KEY (ARTISTA_ID) REFERENCES ARTISTAS(ARTISTA_ID)
) ENGINE = InnoDB;

INSERT INTO USUARIOS (NOME, IDADE, PLANO_ID)
VALUES
('Thati', '23', '1'),
('Cintia', '35', '3'),
('Bill', '20', '2'),
('Roger', '45', '1');

INSERT INTO PLANO (NOME_DO_PLANO, VALOR_DO_PLANO)
VALUES
('gratuito', '0'),
('universitario', '5.99'),
('familiar', '7.99');

INSERT INTO ALBUNS (NOME_DO_ALBUM, ARTISTA_ID)
VALUES
('Envious', '1'),
('Exuberant', '1'),
('Hallowed Steam', '2'),
('Incandescent','3'),
('Temporary Culture', '4');

INSERT INTO ARTISTAS (NOME_DO_ARTISTA)
VALUES
('Walter Phoenix'),
('Peter Strong'),
('Lance Day'),
('Freedie Shannon');

INSERT INTO CANCOES (NOME_DA_CANCAO, ALBUM_ID)
VALUES
('Soul For Us', '11'),
('Reflections Of Magic', '11'),
('Dance With Her Own', '11'),
('Troubles Of My Inner Fire', '12'),
('Time Fireworks', '12'),
('Magic Circus', '13'),
('Honey, So Do I', '13'),
('Sweetie, Lets Go Wild', '13'),
('She Knows', '13'),
('Fantasy For Me', '14'),
('Celebration Of More', '14'),
('Rock His Everything', '14'),
('Home Forever', '14'),
('Diamond Power', '14'),
('Honey, Lets Be Silly', '14'),
('Thang Of Thunder', '15'),
('Words Of Her Life', '15'),
('Without My Streets', '15');

INSERT INTO HIST_REPRODUCOES (USUARIO_ID, CANCAO_ID)
VALUES
('1', '1'),
('1', '6'),
('1', '14'),
('1', '16'),
('2', '13'),
('2', '17'),
('2', '2'),
('2', '15'),
('3', '4'),
('3', '16'),
('3', '6'),
('4', '3'),
('4', '18'),
('4', '11');

INSERT INTO SEGUINDO_ARTISTAS (USUARIO_ID, ARTISTA_ID)
VALUES
('1', '1'),
('1', '4'),
('1', '3'),
('2', '1'),
('2', '3'),
('3', '2'),
('3', '1'),
('4', '4');
