DELIMITER $$
CREATE TRIGGER trigger_usuario_delete
BEFORE DELETE ON
SpotifyClone.USERS
FOR EACH ROW
BEGIN
DELETE FROM SpotifyClone.HISTORY_PLAYED_SONGS WHERE UserID = OLD.UserID;
DELETE FROM SpotifyClone.SINGER_FOLLOWERS WHERE UserID = OLD.UserID;
END $$
DELIMITER ;
