DELIMITER $$

CREATE TRIGGER trigger_usuario_delete
BEFORE DELETE ON SpotifyClone.USERS
FOR EACH ROW
BEGIN
DELETE FROM SpotifyClone.FOLLOWING_ARTISTS WHERE user_id = OLD.user_id;
DELETE FROM SpotifyClone.HISTORY_REPRODUCTIONS WHERE user_id = OLD.user_id;
END $$
DELIMITER ;
