CREATE VIEW top_3_artistas AS
SELECT
A.NOME_DO_ARTISTA AS `artista`,
COUNT(S.USUARIO_ID) AS `seguidores`
FROM SpotifyClone.ARTISTAS AS A
INNER JOIN SpotifyClone.SEGUINDO_ARTISTAS AS S
ON A.ARTISTA_ID = S.ARTISTA_ID
GROUP BY `artista`
ORDER BY `seguidores` DESC, `artista` ASC
LIMIT 3;
