DELIMITER $$

CREATE TRIGGER trigger_usuario_delete
BEFORE DELETE ON SpotifyClone.USER
FOR EACH ROW
BEGIN
 DELETE FROM SpotifyClone.FOLLOWED_ARTISTS WHERE USER_ID=OLD.USER_ID;
 DELETE FROM SpotifyClone.HISTORY_MUSIC WHERE USER_ID=OLD.USER_ID;
END $$

DELIMITER ;
