CREATE VIEW cancoes_premium AS 
SELECT
C.NOME_DA_CANCAO AS `nome`,
COUNT(H.USUARIO_ID) AS `reproducoes`
FROM SpotifyClone.CANCOES AS C
INNER JOIN SpotifyClone.HIST_REPRODUCOES AS H
ON C.CANCAO_ID = H.CANCAO_ID
INNER JOIN SpotifyClone.USUARIOS AS U
ON U.USUARIO_ID = H.USUARIO_ID
WHERE U.PLANO_ID IN (2,3)
GROUP BY C.NOME_DA_CANCAO
ORDER BY `nome` ASC;
